# Generated by Django 3.2.25 on 2024-03-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_update_category_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='update',
            new_name='updated',
        ),
    ]
