# Generated by Django 3.2.25 on 2024-03-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-name'], 'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono'),
        ),
    ]
